name: Test coverage and release
on:
  pull_request_target:
    branches:
      - main

env:
  NODE_VERSION: '21'
  PNPM_VERSION: '9'

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache pnpm Store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install pnpm
        run: npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: Install Dependencies
        run: pnpm install:all

      - name: Run test coverage
        run: pnpm run test:coverage

      - name: List Coverage Directory Contents
        run: ls -R ./coverage

      - name: Upload coverage reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: mio-coverage-reports
          path: ./coverage
  
  upload-coverage:
    runs-on: ubuntu-latest
    needs: test-coverage
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Attempt to Download coverage reports artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          artifact_name: mio-coverage-reports
          path: ./coverage
          search_artifacts: true

      - name: List Downloaded Files
        if: always()
        run: ls -R ./

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          slug: itsferdiardiansa/MediaApp
        with:
          files: ./coverage/merged-coverage.json
          token: ${{ secrets.CODECOV_TOKEN }}
