name: Upload Main Coverage Reports
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.json"
      - "docs/**"
  schedule:
    - cron: "0 0 * * 0"
permissions:
  contents: read
jobs:
  upload-main-coverage:
    uses: ./.github/workflows/wc-upload-coverage.yml