name: Upload Main Coverage Reports
on:
  workflow_run:
    workflows: ["Test coverage"]
    types: 
      - completed
  push:
    branches:
      - main
    paths-ignore:
      - "**.json"
      - "docs/**"
jobs:
  main-branch-coverage-upload:
    uses: ./.github/workflows/wc-upload-coverage.yml
    secrets: inherit