name: wc-upload-coverage
on:
  workflow_call:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download coverage reports artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ vars.COVERAGE_NAME }}
          path: ${{ vars.COVERAGE_PATH }}
          run_id: ${{ github.event.workflow_run.id }}
          search_artifacts: true
          workflow: test-coverage-release.yml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          slug: itsferdiardiansa/MediaApp
        with:
          files: ${{ vars.COVERAGE_FILE_JSON }}
          token: ${{ secrets.CODECOV_TOKEN }}